version: '3'
services:
    nest_service:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        env_file:
            - .env
        volumes:
            - ./src:/app/src
            - ./global.d.ts:/app/global.d.ts
        command: npm run dev
        depends_on:
            - redis_service
        ports:
            - "3000:3000"

    redis_service:
        image: redis:7.2-rc3
        ports:
            - 6379:6379
        restart: always
        volumes: 
            - ./cache:/data
        depends_on:
            - mariadb_service

    mariadb_service:
        image: mariadb:11.1.1-rc-jammy
        restart: always
        env_file:
            - .env
        ports:
            - "3306:3306"
        volumes:
            - ./src/database/scripts/init/:/docker-entrypoint-initdb.d