version: '3'
services:
    api_dev:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        network_mode: host
        env_file:
            - .env
        volumes:
            - ./src:/app/src
            - ./global.d.ts:/app/global.d.ts
        command: npm run dev
        depends_on:
            - redis

    redis:
        image: redis:7.2-rc3
        ports:
            - 6378:6379
        restart: always
        volumes: 
            - ./cache:/data
        depends_on:
            - mariadb

    mariadb:
        image: mariadb:11.1.1-rc-jammy
        restart: always
        env_file:
            - .env
        ports:
            - "3306:3306"
        volumes:
            - ./src/database/scripts/init/:/docker-entrypoint-initdb.d